/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t public/OfficeScene.glb 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Office_Scene: THREE.Mesh;
  };
  materials: {
    OfficeMat: THREE.MeshBasicMaterial;
  };
};

export function OfficeScene(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/OfficeScene.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Office_Scene.geometry}
        material={materials.OfficeMat}
      />
    </group>
  );
}

useGLTF.preload("/OfficeScene.glb");
